### ISSUE TITLE
ImportError: No module named config

### ISSUE THREAD

**Issue by legendsneverdiejp** [Trading-Bot/CryptoBot#78]
> python main.py
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from bot import Crypto_Bot
  File "/home/jp/Desktop/CryptoBot/bot.py", line 8, in <module>
    from config.config import load_config
ImportError: No module named config

config.json exists inside config/ folder.

**Comment by Herklos** [comment]
Hi, where did you start main.py ? 
To start the bot in your environment you have to use : 
```
cd /home/jp/Desktop/CryptoBot
python3 main.py
```

**Comment by legendsneverdiejp** [comment]
This is so weird. I repeated the same steps, and now i'm getting a different error.

Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from bot import Crypto_Bot
  File "/home/jp/Desktop/CryptoBot/bot.py", line 6, in <module>
    import ccxt
ImportError: No module named 'ccxt'

**Comment by GuillaumeDSM** [comment]
Hi !
You need to install the modules listed in requirement.txt.
From ReadMe:
Install
```
git clone https://github.com/Trading-Bot/CryptoBot
cd CryptoBot
sudo pip install -r requirements.txt
```
If you have additional problems, please check [https://github.com/Trading-Bot/CryptoBot/wiki/Installation ](https://github.com/Trading-Bot/CryptoBot/wiki/Installation) !

**Comment by legendsneverdiejp** [comment]
Ok, i started from 0, this is my step by step process:
1-  go to Desktop from terminal, and run git clone https://github.com/Trading-Bot/CryptoBot
2- cd CryptoBot
3- sudo -H pip install -r requirements.txt
output: https://pastebin.com/M9Pgkxnx
4- (i know that now i should add the config file, but just to be sure error is gone i run:) python3.6 main.py (tested with just python3 too)
and here is the error output:

**Comment by Herklos** [comment]
We never had this problem but I found a solution [here](https://stackoverflow.com/questions/13708180/python-dev-installation-error-importerror-no-module-named-apt-pkg)
